#ifndef __H_STDAFX__
#define __H_STDAFX__
#define NUM_OF_PROCESS_BARS	2
#define PROCESS_BAR_WIDTH	80
#define PROCESS_BAR_HEIGHT	40
#define FRAMES_PER_SECOND	60
#define WINDOW_WIDTH		(NUM_OF_PROCESS_BARS * PROCESS_BAR_WIDTH + (PROCESS_BAR_HEIGHT >> 1))
#define WINDOW_HEIGHT		PROCESS_BAR_HEIGHT
#define HIDE_COMMAND_WINDOW	1

#endif
